#!/bin/bash
# ----------------------------------------------------------------------
# Copyright (c) 20121 astrorafael@gmail.com.
#
# See the LICENSE file for details
# ----------------------------------------------------------------------
python -m tesslabel -c -d $HOME/tesslabel/tesslabel.db -l $HOME/tesslabel/tesslabel.log gui $*
